name: Build binaries for team_scraper.py
on:
  release:
    types: [created, edited, published, prereleased, released]

jobs:
    build:
      strategy:
        matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]
      concurrency:
        group: build-team_scraper-${{ matrix.os }}
        cancel-in-progress: true
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v4.7.1
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Build binaries
          run: |
            pyinstaller --onefile --noconsole team_scraper.py
        - name: Upload binaries
          uses: actions/upload-artifact@v2
          with:
            name: team_scraper
            path: dist/team_scraper
